# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caa2f4659abda707b24970c885e67137b9e08af77d0487de7cb331b04498a3547dcb0b82f65fac8674cfc6200882f27d92c910a5e7e8fbf0685e1e0c6edc511b

test:
  secret_key_base: 2bf58c0f30772b11114bd82d437e9c0b4d4ea680736002cc2e985e469bda9cab6ca374e576d6aa818ea6822d91c6f0bec8c1530921b6b869febab4047c32d89b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
